//! レビュー面（内蔵`ReviewPanel`）の手動E2E用フィクスチャ生成器。
//!
//! ```text
//! cargo run -p harness-cli --example review-e2e-fixtures -- <出力ディレクトリ>
//! ```
//!
//! **なぜ実装コード経由で作るのか**: ステージ済み変更の実体は「オーバーレイのファイル＋
//! 操作台帳（`.harness-cow-ops.jsonl`）＋baselineミラー」の3点セットで、台帳の`baseline_hash`は
//! `harness_change_ledger::hash_bytes`（Rustの`DefaultHasher`）でなければならない。手書きや
//! 外部スクリプトで作ると必ずずれ、`apply`が全件conflictになる。ここでは実際の
//! `SandboxFs::write_string`/`remove`を呼ぶので、製品が書くものとバイト単位で同じになる。
//!
//! 生成物:
//!
//! - `<out>/cow/` — 8シナリオ分のワークスペース。各シナリオが1セッション
//!   （`.harness/sessions/session-<id>.jsonl`）＋1オーバーレイ（`.harness/sandbox/session-<id>/`）
//!   を持ち、`harness --staged --resume <id>`で開くとその変更だけがレビュー対象になる。
//! - `%APPDATA%\harness\data\memory\<workspace-key>\` — Recall記憶のレビュー用データ4種
//!   （`plans/PLAN-RECALL-MEMORY.md`）。**`RecallStore`経由で作る**ので、
//!   `harness memory list --all`・TUIの`/memory`からそのまま見える。

use std::path::{Path, PathBuf};

use harness_cognition::{Checkpoint, CheckpointMeta, RecallStore, ReviewedWatermark};
use harness_core::{ContentBlock, Message, Role, StagingConfig, StagingMode};
use harness_engine::SessionStore;
use harness_sandbox::SandboxFs;

/// 生成物であることの目印。既存ディレクトリを消す前にこれを確認する。
const MARKER: &str = "REVIEW-E2E-FIXTURES.md";

fn main() {
    let mut args = std::env::args().skip(1);
    let Some(out) = args.next() else {
        eprintln!("usage: cargo run -p harness-cli --example review-e2e-fixtures -- <out-dir>");
        std::process::exit(2);
    };
    let out = PathBuf::from(out);
    prepare_root(&out);

    let cow_ws = out.join("cow");
    std::fs::create_dir_all(cow_ws.join(".harness").join("sessions")).unwrap();
    build_cow_scenarios(&cow_ws);

    let recall_roots = build_recall_fixtures(&out);
    let combo = build_combo(&out);

    write_readme(&out, &cow_ws, &recall_roots, combo.as_ref());
    println!("\n生成しました: {}", out.display());
    println!("次に読むもの: {}", out.join(MARKER).display());
}

/// 出力先を空にする。**目印ファイルが無い既存ディレクトリは消さない**（生成器に他人の
/// ディレクトリを消させない）。
fn prepare_root(out: &Path) {
    if out.exists() {
        if !out.join(MARKER).exists() {
            eprintln!(
                "refusing to overwrite {}: it exists and has no {MARKER} marker",
                out.display()
            );
            std::process::exit(2);
        }
        std::fs::remove_dir_all(out).expect("remove previous fixtures");
    }
    std::fs::create_dir_all(out).expect("create out dir");
    std::fs::write(out.join(MARKER), "generated by review-e2e-fixtures\n").unwrap();
}

// ---------------------------------------------------------------- CoW/staged

struct Scenario {
    /// `--resume <id>`に渡す識別子（セッションファイル名は`session-<id>.jsonl`）。
    id: &'static str,
    /// `/sessions`一覧に出る1行目（最初のユーザー発話）。
    headline: String,
    /// パネルで何を見るか（READMEに出す）。
    expect: &'static str,
    /// 会話（セッションファイルへ書く）。
    conversation: Vec<Message>,
    /// **生成後に実際の`review_file`で数えた**エントリ内訳。手書きの期待値ではなく、
    /// パネルが本当に出すものを一覧へ書き出すため。
    files: Vec<FileFacts>,
}

struct FileFacts {
    path: String,
    op: String,
    hunks: usize,
    block: Option<String>,
}

fn build_cow_scenarios(ws: &Path) {
    let scenarios = [
        multi_short(ws),
        multi_long(ws),
        single_modify_short(ws),
        single_modify_long(ws),
        single_create_short(ws),
        single_create_long(ws),
        single_delete_short(ws),
        single_delete_long(ws),
    ];
    let sessions_dir = ws.join(".harness").join("sessions");
    for s in &scenarios {
        let store = SessionStore::open(sessions_dir.join(format!("session-{}.jsonl", s.id)));
        store.append_messages(&s.conversation).unwrap();
        println!("[cow] session-{:<22} {}", s.id, s.expect);
    }
    std::fs::write(ws.join("SCENARIOS.md"), scenario_table(&scenarios)).unwrap();
}

fn scenario_table(scenarios: &[Scenario]) -> String {
    let mut out = String::from(
        "# CoW/stagedシナリオ一覧\n\n\
         各シナリオは`harness.exe --staged --resume <id>`で開く（レビュー対象は**起動時の\n\
         セッション**で決まる。TUI内の`/sessions`では会話だけが切り替わり、レビュー対象は\n\
         切り替わらない）。\n\n\
         | `--resume` | 会話 | 件数 | 見どころ |\n|---|---|---|---|\n",
    );
    for s in scenarios {
        out.push_str(&format!(
            "| `{}` | {}件・{} | {} | {} |\n",
            s.id,
            s.conversation.len(),
            if s.conversation.len() > 4 { "長文" } else { "短文" },
            s.files.len(),
            s.expect
        ));
    }
    out.push_str("\n## エントリ内訳（`review_file`の実測値）\n\n");
    for s in scenarios {
        out.push_str(&format!("### `{}`\n\n> {}\n\n", s.id, s.headline));
        out.push_str("| パス | 操作 | ハンク数 | ハンク操作 |\n|---|---|---|---|\n");
        for f in &s.files {
            out.push_str(&format!(
                "| `{}` | {} | {} | {} |\n",
                f.path,
                f.op,
                f.hunks,
                match &f.block {
                    None => "可".to_string(),
                    Some(reason) => format!("不可（{reason}）"),
                }
            ));
        }
        out.push('\n');
    }
    out
}

/// 1シナリオ分のオーバーレイを作る。`seed`が実workspace側の元の姿、`edit`がエージェントの
/// 書込み（オーバーレイ＋台帳＋baselineミラーがここで実際に作られる）。
///
/// 戻り値は**製品コード（`review_file`）が実際に計算した**内訳。一覧に手書きの期待値を
/// 載せると、生成物と食い違ったときにE2Eの時間を無駄にするため、事実だけを書き出す。
fn staged_overlay(
    ws: &Path,
    id: &str,
    seed: impl Fn(&Path),
    edit: impl Fn(&SandboxFs),
) -> Vec<FileFacts> {
    seed(ws);
    let staging = StagingConfig {
        mode: StagingMode::Staged,
        sandbox_dir: Some(
            PathBuf::from(".harness")
                .join("sandbox")
                .join(format!("session-{id}")),
        ),
    };
    let fs = SandboxFs::open(ws, &staging).expect("open sandbox");
    edit(&fs);
    fs.change_set()
        .expect("change set")
        .iter()
        .map(|entry| {
            let review = fs.review_file(entry);
            FileFacts {
                path: entry.path.clone(),
                op: format!("{:?}", entry.op),
                hunks: review.hunks.len(),
                block: review.hunk_block.map(|b| b.reason().to_string()),
            }
        })
        .collect()
}

fn write_file(ws: &Path, rel: &str, content: &str) {
    let path = ws.join(rel);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, content).unwrap();
}

fn write_bytes(ws: &Path, rel: &str, content: &[u8]) {
    let path = ws.join(rel);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, content).unwrap();
}

// ---- 本文の材料 ----

fn short_ts(title: &str) -> String {
    format!(
        "// {title}\n\
         export function main() {{\n\
         \x20 const name = \"world\";\n\
         \x20 console.log(`hello ${{name}}`);\n\
         }}\n\
         \n\
         export function add(a: number, b: number) {{\n\
         \x20 return a + b;\n\
         }}\n\
         \n\
         export function sub(a: number, b: number) {{\n\
         \x20 return a - b;\n\
         }}\n\
         \n\
         export const VERSION = \"0.1.0\";\n\
         export const DEBUG = false;\n\
         export const RETRIES = 3;\n\
         export const TIMEOUT_MS = 1000;\n"
    )
}

/// `lines`行の疑似Rustソース。行番号を埋め込んであるので、どのハンクを見ているかが分かる。
fn long_rs(lines: usize) -> String {
    let mut out = String::from("//! 長文シナリオ用の疑似モジュール（自動生成）。\n\nuse std::collections::HashMap;\n\n");
    for i in 0..lines {
        match i % 12 {
            0 => out.push_str(&format!("/// 手続き{i}の説明。ここは変更されない文脈行です。\n")),
            1 => out.push_str(&format!("pub fn step_{i}(input: &str) -> String {{\n")),
            2 => out.push_str(&format!("    let mut buf = String::with_capacity({});\n", i * 8)),
            3 => out.push_str("    for (idx, ch) in input.char_indices() {\n"),
            4 => out.push_str("        if idx % 2 == 0 {\n"),
            5 => out.push_str("            buf.push(ch.to_ascii_uppercase());\n"),
            6 => out.push_str("        } else {\n"),
            7 => out.push_str("            buf.push(ch);\n"),
            8 => out.push_str("        }\n"),
            9 => out.push_str("    }\n"),
            10 => out.push_str("    buf\n"),
            _ => out.push_str("}\n\n"),
        }
    }
    out
}

/// 日本語の長文ドキュメント。**折り返し無しのdiffペインで右端が切れる長い行**を混ぜてある。
fn long_ja_doc(sections: usize) -> String {
    let mut out = String::from("# 運用ガイド（自動生成の長文サンプル）\n\n");
    for i in 0..sections {
        out.push_str(&format!("## {i}. 節タイトル{i}\n\n"));
        out.push_str(&format!(
            "この節は自動生成された説明文です（節番号{i}）。レビューパネルの表示確認のために、\n\
             短い行と長い行を混在させています。\n"
        ));
        out.push_str(&format!(
            "長い行の例（{i}）: {}\n\n",
            "この行はdiffペインの右端で切れることを確認するための非常に長い一行です。".repeat(4)
        ));
    }
    out
}

fn tool_call(id: &str, name: &str, input: serde_json::Value, output: &str) -> Vec<Message> {
    vec![
        Message {
            role: Role::Assistant,
            content: vec![ContentBlock::ToolUse {
                id: id.to_string(),
                name: name.to_string(),
                input,
            }],
        },
        Message {
            role: Role::User,
            content: vec![ContentBlock::ToolResult {
                tool_use_id: id.to_string(),
                content: output.to_string(),
                is_error: false,
            }],
        },
    ]
}

fn user(text: &str) -> Message {
    Message {
        role: Role::User,
        content: vec![ContentBlock::Text(text.to_string())],
    }
}

fn assistant(text: &str) -> Message {
    Message {
        role: Role::Assistant,
        content: vec![ContentBlock::Text(text.to_string())],
    }
}

/// 長い会話（transcriptのスクロール・折り畳みも一緒に見るため）。
fn long_conversation(topic: &str, extra: &str) -> Vec<Message> {
    let mut msgs = vec![
        user(&format!(
            "{topic}。長文シナリオなので、変更の意図と影響範囲を詳しく説明しながら進めてください。"
        )),
        assistant(&format!(
            "承知しました。まず対象を把握します。{extra}\n\n\
             このセッションは**レビューパネルの手動E2E用に生成された会話データ**で、実際のモデル\n\
             呼び出しは行われていません。以下の説明はパネルの見え方（長い本文・折り畳み・\n\
             スクロール）を確認するための埋め草です。\n\n\
             {}",
            "処理の各段階について、入力・出力・失敗時の挙動を順に述べます。".repeat(6)
        )),
    ];
    msgs.extend(tool_call(
        "call_glob_1",
        "glob",
        serde_json::json!({ "pattern": "**/*.rs" }),
        "matched 3 files",
    ));
    msgs.push(assistant(&format!(
        "対象が分かったので編集します。\n\n{}",
        "変更点は互いに離れた位置にあるため、レビューでは複数のハンクとして表示されるはずです。"
            .repeat(5)
    )));
    msgs.extend(tool_call(
        "call_edit_1",
        "edit_file",
        serde_json::json!({
            "path": "example.rs",
            "old_string": "let mut buf = String::new();",
            "new_string": "let mut buf = String::with_capacity(64);"
        }),
        "edited",
    ));
    msgs.push(assistant(
        "編集が終わりました。`/fsstage commit`（またはスラッシュコマンド）でパネルを開き、\n\
         ハンク単位で採否を決めてください。",
    ));
    msgs
}

fn short_conversation(topic: &str, done: &str) -> Vec<Message> {
    vec![
        user(topic),
        assistant(done),
        user("ではレビューします。"),
        assistant("`/fsstage commit`でパネルを開けます。"),
    ]
}

// ---- 8シナリオ ----

fn multi_short(ws: &Path) -> Scenario {
    let id = "multi-short";
    let files = staged_overlay(
        ws,
        id,
        |ws| {
            write_file(ws, "multi-short/src/app.ts", &short_ts("app entry"));
            write_file(ws, "multi-short/config.json", "{\n  \"name\": \"demo\",\n  \"retries\": 3\n}\n");
            write_file(ws, "multi-short/notes/todo.md", "- [ ] 古いTODO\n- [ ] もう使っていない\n");
        },
        |fs| {
            // 離れた2箇所を変える（＝ハンク2つ）。
            let modified = short_ts("app entry")
                .replace("const name = \"world\";", "const name = \"harness\";")
                .replace("export const RETRIES = 3;", "export const RETRIES = 5;");
            fs.write_string("multi-short/src/app.ts", &modified).unwrap();
            fs.write_string(
                "multi-short/config.json",
                "{\n  \"name\": \"demo\",\n  \"retries\": 5\n}\n",
            )
            .unwrap();
            fs.write_string(
                "multi-short/src/util.ts",
                "export function clamp(v: number, lo: number, hi: number) {\n  return Math.min(hi, Math.max(lo, v));\n}\n",
            )
            .unwrap();
            fs.remove("multi-short/notes/todo.md").unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "リトライ回数を5に上げて、使っていないTODOを消して".to_string(),
        expect: "4件（M 2件・A 1件・D 1件）。`app.ts`が2ハンク、他は1ハンク/全体",
        conversation: short_conversation(
            "リトライ回数を5に上げて、使っていないTODOを消して",
            "app.ts・config.jsonを変更し、util.tsを追加、notes/todo.mdを削除しました。",
        ),
    }
}

fn multi_long(ws: &Path) -> Scenario {
    let id = "multi-long";
    let files = staged_overlay(
        ws,
        id,
        |ws| {
            write_file(ws, "multi-long/src/engine.rs", &long_rs(320));
            write_file(ws, "multi-long/docs/guide.md", &long_ja_doc(14));
            write_file(ws, "multi-long/legacy/old_module.rs", &long_rs(120));
            // CRLFのファイル（部分適用で改行が壊れないことを目で見る）。
            write_file(
                ws,
                "multi-long/data/win.txt",
                &long_rs(60).replace('\n', "\r\n"),
            );
            // 非UTF-8（「preview only」の注記が出る）。
            write_bytes(
                ws,
                "multi-long/assets/blob.bin",
                &[0x00, 0xff, 0xfe, b'b', b'i', b'n', 0x80, b'\n'],
            );
        },
        |fs| {
            let long = long_rs(320);
            let modified = long
                .replace("pub fn step_1(", "pub fn step_1_renamed(")
                .replace("pub fn step_97(", "pub fn step_97_renamed(")
                .replace("pub fn step_193(", "pub fn step_193_renamed(")
                .replace("pub fn step_301(", "pub fn step_301_renamed(");
            fs.write_string("multi-long/src/engine.rs", &modified).unwrap();

            let doc = long_ja_doc(14)
                .replace("## 0. 節タイトル0", "## 0. 節タイトル0（改訂）")
                .replace("## 7. 節タイトル7", "## 7. 節タイトル7（改訂）")
                .replace("## 13. 節タイトル13", "## 13. 節タイトル13（改訂）");
            fs.write_string("multi-long/docs/guide.md", &doc).unwrap();

            fs.write_string("multi-long/src/generated_report.md", &long_ja_doc(10))
                .unwrap();
            fs.remove("multi-long/legacy/old_module.rs").unwrap();

            let crlf = long_rs(60)
                .replace("pub fn step_1(", "pub fn step_1_renamed(")
                .replace("pub fn step_49(", "pub fn step_49_renamed(")
                .replace('\n', "\r\n");
            fs.write_string("multi-long/data/win.txt", &crlf).unwrap();

            fs.write_string("multi-long/assets/blob.bin", "テキストで上書きした\n")
                .unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "エンジンとガイドを一括で改訂して、旧モジュールを撤去して".to_string(),
        expect: "6件（M 4件・A 1件・D 1件）。`engine.rs`は4ハンク、`win.txt`はCRLF、`blob.bin`は非UTF-8で降格",
        conversation: long_conversation(
            "エンジンとガイドを一括で改訂して、旧モジュールを撤去して",
            "`multi-long/`配下を対象に、engine.rs・guide.md・win.txtを改訂します。",
        ),
    }
}

fn single_modify_short(ws: &Path) -> Scenario {
    let id = "single-modify-short";
    let files = staged_overlay(
        ws,
        id,
        |ws| write_file(ws, "single-modify-short/src/app.ts", &short_ts("single edit")),
        |fs| {
            let modified = short_ts("single edit")
                .replace("export const DEBUG = false;", "export const DEBUG = true;");
            fs.write_string("single-modify-short/src/app.ts", &modified)
                .unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "デバッグフラグを有効にして".to_string(),
        expect: "1件（M）。1ハンクだけ",
        conversation: short_conversation(
            "デバッグフラグを有効にして",
            "`DEBUG`を`true`にしました。",
        ),
    }
}

fn single_modify_long(ws: &Path) -> Scenario {
    let id = "single-modify-long";
    let files = staged_overlay(
        ws,
        id,
        |ws| write_file(ws, "single-modify-long/src/engine.rs", &long_rs(600)),
        |fs| {
            let mut modified = long_rs(600);
            for n in [13, 121, 253, 397, 517] {
                modified = modified.replace(
                    &format!("pub fn step_{n}("),
                    &format!("pub fn step_{n}_renamed("),
                );
            }
            fs.write_string("single-modify-long/src/engine.rs", &modified)
                .unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "エンジンの命名を5箇所そろえて".to_string(),
        expect: "1件（M）。**5ハンク**——Tab→↑↓でハンク間を移動し、一部だけacceptする確認用",
        conversation: long_conversation(
            "エンジンの命名を5箇所そろえて",
            "`single-modify-long/src/engine.rs`の関数名を5箇所そろえます。",
        ),
    }
}

fn single_create_short(ws: &Path) -> Scenario {
    let id = "single-create-short";
    let files = staged_overlay(
        ws,
        id,
        |_ws| {},
        |fs| {
            fs.write_string(
                "single-create-short/CHANGELOG.md",
                "# 変更履歴\n\n## 0.1.0\n\n- 初回リリース\n",
            )
            .unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "CHANGELOGを作って".to_string(),
        expect: "1件（A）。全行が追加、ハンク操作は**無効**（全か無か）",
        conversation: short_conversation("CHANGELOGを作って", "CHANGELOG.mdを新規作成しました。"),
    }
}

fn single_create_long(ws: &Path) -> Scenario {
    let id = "single-create-long";
    let files = staged_overlay(
        ws,
        id,
        |_ws| {},
        |fs| {
            fs.write_string("single-create-long/docs/design.md", &long_ja_doc(20))
                .unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "設計ドキュメントの草案を書いて".to_string(),
        expect: "1件（A）。長文の新規ファイル——PgUp/PgDnでdiffペインを最後まで送れるかの確認用",
        conversation: long_conversation(
            "設計ドキュメントの草案を書いて",
            "`single-create-long/docs/design.md`として新規に書き起こします。",
        ),
    }
}

fn single_delete_short(ws: &Path) -> Scenario {
    let id = "single-delete-short";
    let files = staged_overlay(
        ws,
        id,
        |ws| write_file(ws, "single-delete-short/notes/scratch.md", "- 一時メモ\n- 消してよい\n"),
        |fs| fs.remove("single-delete-short/notes/scratch.md").unwrap(),
    );
    Scenario {
        id,
        files,
        headline: "一時メモを消して".to_string(),
        expect: "1件（D）。全行が削除、ハンク操作は**無効**",
        conversation: short_conversation("一時メモを消して", "notes/scratch.mdを削除しました。"),
    }
}

fn single_delete_long(ws: &Path) -> Scenario {
    let id = "single-delete-long";
    let files = staged_overlay(
        ws,
        id,
        |ws| write_file(ws, "single-delete-long/legacy/huge_module.rs", &long_rs(400)),
        |fs| fs.remove("single-delete-long/legacy/huge_module.rs").unwrap(),
    );
    Scenario {
        id,
        files,
        headline: "使われていない巨大モジュールを撤去して".to_string(),
        expect: "1件（D）。長文が全行削除として出る",
        conversation: long_conversation(
            "使われていない巨大モジュールを撤去して",
            "`single-delete-long/legacy/huge_module.rs`を削除対象にします。",
        ),
    }
}

// -------------------------------------------------------- 欲張りセット（両方）

/// **CoWの未適用変更とRecallの未レビュー記憶が同時に存在する**ワークスペース。
/// 記憶はワークスペース単位（セッション単位ではない）なので、2つのセッションが同じ記憶
/// ディレクトリを共有する——「どのセッションで開いても未レビュー記憶は同じ」という
/// 設計どおりの見え方をそのまま再現している。
fn build_combo(out: &Path) -> Option<ComboFixture> {
    let ws = out.join("combo");
    std::fs::create_dir_all(ws.join(".harness").join("sessions")).unwrap();

    let scenarios = [combo_short(&ws), combo_long(&ws)];
    let sessions_dir = ws.join(".harness").join("sessions");
    for s in &scenarios {
        let store = SessionStore::open(sessions_dir.join(format!("session-{}.jsonl", s.id)));
        store.append_messages(&s.conversation).unwrap();
        println!("[combo] session-{:<22} {}", s.id, s.expect);
    }
    std::fs::write(ws.join("SCENARIOS.md"), scenario_table(&scenarios)).unwrap();

    // 8件のうち先頭3件をレビュー済みにする（ウォーターマークを添字2へ進める）＝
    // 残り5件（短文2・長文3）が未レビュー。
    let specs: Vec<CheckpointSpec> = (0..8).map(|i| CheckpointSpec::new(i, i >= 5)).collect();
    let dir = write_memory(&ws, &specs, Some(2))?;
    println!("[combo] memory -> {} (8件中5件が未レビュー)", dir.display());
    Some(ComboFixture {
        workspace: ws,
        memory: dir,
    })
}

struct ComboFixture {
    workspace: PathBuf,
    memory: PathBuf,
}

fn combo_short(ws: &Path) -> Scenario {
    let id = "combo-short";
    let files = staged_overlay(
        ws,
        id,
        |ws| {
            write_file(ws, "combo-short/src/app.ts", &short_ts("combo entry"));
            write_file(ws, "combo-short/notes/scratch.md", "- 消す予定のメモ\n");
        },
        |fs| {
            let modified = short_ts("combo entry")
                .replace("const name = \"world\";", "const name = \"combo\";")
                .replace("export const TIMEOUT_MS = 1000;", "export const TIMEOUT_MS = 2500;");
            fs.write_string("combo-short/src/app.ts", &modified).unwrap();
            fs.write_string("combo-short/src/flags.ts", "export const FEATURE_X = true;\n")
                .unwrap();
            fs.remove("combo-short/notes/scratch.md").unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "タイムアウトを伸ばして、要らないメモを消して".to_string(),
        expect: "CoW 3件（M/A/D）＋未レビュー記憶5件。短文",
        conversation: short_conversation(
            "タイムアウトを伸ばして、要らないメモを消して",
            "app.tsを変更し、flags.tsを追加、scratch.mdを削除しました。過去の記憶も5件たまっています。",
        ),
    }
}

fn combo_long(ws: &Path) -> Scenario {
    let id = "combo-long";
    let files = staged_overlay(
        ws,
        id,
        |ws| {
            write_file(ws, "combo-long/src/engine.rs", &long_rs(480));
            write_file(ws, "combo-long/docs/guide.md", &long_ja_doc(16));
            write_file(ws, "combo-long/legacy/dead.rs", &long_rs(90));
        },
        |fs| {
            let mut modified = long_rs(480);
            for n in [25, 157, 289, 421] {
                modified = modified.replace(
                    &format!("pub fn step_{n}("),
                    &format!("pub fn step_{n}_renamed("),
                );
            }
            fs.write_string("combo-long/src/engine.rs", &modified).unwrap();
            let doc = long_ja_doc(16)
                .replace("## 2. 節タイトル2", "## 2. 節タイトル2（改訂）")
                .replace("## 11. 節タイトル11", "## 11. 節タイトル11（改訂）");
            fs.write_string("combo-long/docs/guide.md", &doc).unwrap();
            fs.write_string("combo-long/docs/appendix.md", &long_ja_doc(12))
                .unwrap();
            fs.remove("combo-long/legacy/dead.rs").unwrap();
        },
    );
    Scenario {
        id,
        files,
        headline: "エンジンとガイドを改訂しつつ、死んだコードを落として".to_string(),
        expect: "CoW 4件（M2/A1/D1、engine.rsは4ハンク）＋未レビュー記憶5件。長文",
        conversation: long_conversation(
            "エンジンとガイドを改訂しつつ、死んだコードを落として",
            "`combo-long/`配下を対象にします。過去セッションの記憶も未レビューで残っています。",
        ),
    }
}

// ------------------------------------------------------------------- Recall

/// Recallの記憶データを**実装コード経由で**作る（`plans/PLAN-RECALL-MEMORY.md`）。
///
/// 置き場（`ProjectDirs::data_dir()`配下`memory/<workspace-key>/`）・workspace-keyの畳み込み・
/// ID検証・front matterの形・`index.jsonl`・`reviewed.json`・git履歴化は、全て
/// `RecallStore::append`／`mark_reviewed`が決める。**ここで同じ形式を書き下ろさない**——
/// 以前この生成器は設計書の記述から形式を推測して手書きしており、実装と4点
/// （置き場・keyの桁数・`created_at_ms`・ウォーターマークの形）で食い違って、生成しても
/// `harness memory list`から1件も見えない状態になっていた（`bug-pattern-rules` B-05:
/// コンパイラが守らない複製は静かにずれる）。
fn build_recall_fixtures(out: &Path) -> Vec<(PathBuf, PathBuf)> {
    let variants: [(&str, usize, bool); 4] = [
        ("recall-multi-short", 6, false),
        ("recall-multi-long", 5, true),
        ("recall-single-short", 1, false),
        ("recall-single-long", 1, true),
    ];
    let mut made = Vec::new();
    for (name, count, long) in variants {
        let ws = out.join(name);
        std::fs::create_dir_all(&ws).unwrap();
        std::fs::write(
            ws.join("README.md"),
            format!("# {name}\n\nRecall記憶レビューのフィクスチャ用ワークスペース（中身は空でよい）。\n"),
        )
        .unwrap();
        let specs: Vec<CheckpointSpec> = (0..count).map(|i| CheckpointSpec::new(i, long)).collect();
        // ウォーターマークを進めない＝**全件が未レビュー**になる（既定の`ReviewedWatermark`は
        // `{created_at_ms: 0, id: ""}`で、どのcheckpointよりも小さい）。
        let Some(dir) = write_memory(&ws, &specs, None) else {
            eprintln!("warning: 記憶ディレクトリを用意できなかったためRecallデータを作りませんでした");
            return made;
        };
        println!("[recall] {name} -> {}", dir.display());
        made.push((ws, dir));
    }
    made
}

/// フィクスチャの`created_at_ms`の基点。**固定値**にすることで、生成し直しても同じIDになる
/// （`recall_e2e.rs`の台本がIDをリテラルで参照できる）。
const FIXTURE_EPOCH_MS: u64 = 1_785_000_000_000;

struct CheckpointSpec {
    seq: usize,
    long: bool,
}

impl CheckpointSpec {
    fn new(seq: usize, long: bool) -> Self {
        Self { seq, long }
    }

    fn created_at_ms(&self) -> u64 {
        FIXTURE_EPOCH_MS + self.seq as u64 * 3_600_000
    }

    /// 決定的なID。`cp-<epoch millis>-<8hex>`という実装の採番規約
    /// （`recall/checkpoint.rs::make_id`）に合わせるが、本文ハッシュではなく連番から作る
    /// （再生成しても変わらないようにするため）。
    fn id(&self) -> String {
        format!("cp-{}-{:08x}", self.created_at_ms(), self.seq)
    }

    fn summary(&self) -> String {
        if self.long {
            format!(
                "{}件目の記憶: AppContainer配下の書込み経路と、そこで確定した判断の要約（長文サンプル）",
                self.seq
            )
        } else {
            format!("{}件目の記憶: 短い要約サンプル", self.seq)
        }
    }

    fn checkpoint(&self) -> Checkpoint {
        Checkpoint {
            meta: CheckpointMeta {
                id: self.id(),
                created_at_ms: self.created_at_ms(),
                tags: vec![
                    "sandbox".to_string(),
                    "tier2a".to_string(),
                    if self.long { "長文" } else { "短文" }.to_string(),
                ],
                summary: self.summary(),
                goal_excerpt: format!("ゴール{}: レビュー面のE2Eで使う記憶データ", self.seq),
                // File出典のダイジェストは入れない（＝recall時のFreshnessは`Stale`側に倒れる）。
                // ここで作りたいのは「レビュー運用の見え方」であって鮮度判定ではないため。
                sources: Vec::new(),
            },
            body: checkpoint_body(self),
        }
    }
}

/// 1ワークスペース分の記憶を`RecallStore`経由で作る。`reviewed_upto`に添字を渡すと、
/// そこまでをレビュー済みにする（ウォーターマーク方式なので、それより新しい分が未レビュー）。
fn write_memory(
    ws: &Path,
    specs: &[CheckpointSpec],
    reviewed_upto: Option<usize>,
) -> Option<PathBuf> {
    let store = match RecallStore::for_workspace(ws) {
        Ok(s) => s,
        Err(reason) => {
            eprintln!("warning: 記憶ディレクトリを解決できませんでした: {reason}");
            return None;
        }
    };
    // 前回の生成物を捨てる。**製品の撤収経路（`harness memory forget`と同じ`forget()`）を
    // そのまま使う**——生成器が独自に`remove_dir_all`すると、消し方が実装とずれる。
    if let Err(e) = store.forget() {
        eprintln!("warning: 既存の記憶を削除できませんでした: {e}");
        return None;
    }
    for spec in specs {
        // `allow_unversioned = true`: gitが無い環境でもフィクスチャは作れるようにする
        // （gitがあれば`append`が1書込み1コミットで履歴化する）。
        if let Err(reason) = store.append(&spec.checkpoint(), true) {
            eprintln!("warning: checkpointを書けませんでした: {reason}");
            return None;
        }
    }
    if let Some(i) = reviewed_upto {
        let spec = &specs[i];
        store.mark_reviewed(ReviewedWatermark {
            created_at_ms: spec.created_at_ms(),
            id: spec.id(),
        });
    }
    Some(store.dir().to_path_buf())
}

/// checkpoint本体のMarkdown（front matterは`RecallStore`が付ける）。
fn checkpoint_body(spec: &CheckpointSpec) -> String {
    let (i, long) = (spec.seq, spec.long);
    let mut out = format!(
        "## ゴール\n\n\
         レビュー面のE2Eで使う記憶データ（{i}件目）。\n\n\
         ## 確証済みの要点\n\n"
    );
    if long {
        for n in 0..12 {
            out.push_str(&format!(
                "- 要点{n}: {}\n",
                "この行は長文シナリオ用の埋め草で、記憶レビューのdiffペインで折り返しなしに右端が切れることを確認するためのものです。".repeat(2)
            ));
        }
        out.push_str("\n## 出典\n\n");
        for n in 0..8 {
            out.push_str(&format!("- File: `crates/harness-sandbox/src/module_{n}.rs`\n"));
        }
    } else {
        out.push_str("- 要点1: 短い記憶のサンプル。\n- 要点2: 2行目。\n\n## 出典\n\n- File: `README.md`\n");
    }
    out
}

// ------------------------------------------------------------------- README

fn write_readme(
    out: &Path,
    cow_ws: &Path,
    recall: &[(PathBuf, PathBuf)],
    combo: Option<&ComboFixture>,
) {
    let mut body = format!(
        "# レビュー面 手動E2Eフィクスチャ\n\n\
         `cargo run -p harness-cli --example review-e2e-fixtures -- {}`が生成したもの。\n\
         再実行すると**この中身は作り直される**（このファイルが目印）。\n\n\
         ## CoW/staged（内蔵ReviewPanelで今すぐ試せる）\n\n\
         ワークスペース: `{}`\n\n\
         **シナリオごとに`--resume`で起動する。** レビューパネルが見るオーバーレイは\n\
         **起動時のセッション**で決まるため、TUI内の`/sessions`で会話を切り替えても\n\
         レビュー対象は切り替わらない（会話だけが変わる）。\n\n\
         ```powershell\n\
         cd {}\n\
         harness.exe --staged --resume multi-short\n\
         ```\n\n\
         起動したら`/fsstage commit`でパネルを開く。キーは\n\
         `↑↓`一覧・`Enter/Space`行トグル・`Tab`でdiffペインへ・`↑↓`ハンク移動・\n\
         `Enter/Space`ハンクトグル・`PgUp/PgDn`スクロール・`c`コミット・`x`全破棄・`Esc`閉じる。\n\n\
         シナリオ一覧は`cow/SCENARIOS.md`。\n\n\
         ## Recall記憶\n\n\
         `RecallStore`経由で作ってあるので、そのまま開ける。\n\n\
         ```powershell\n\
         cd <下表のワークスペース>\n\
         harness.exe memory list --all      # 一覧（既定は未レビュー分のみ）\n\
         harness.exe memory show <id>       # 本文\n\
         harness.exe memory review --mark-reviewed\n\
         ```\n\n\
         TUIからは`/memory`（`list`/`reviewed`/`discard <id>`）。起動時に未レビュー件数が\n\
         1行通知される。**内蔵`ReviewPanel`のRecall面はまだ無い**\n\
         （`plans/PLAN-VSCODE-REVIEW.md`側の未実装分）。\n\n",
        out.display(),
        cow_ws.display(),
        cow_ws.display()
    );
    if recall.is_empty() {
        body.push_str("（記憶ディレクトリを解決できなかったため未生成）\n");
    } else {
        body.push_str("| ワークスペース | 記憶ディレクトリ | 件数 |\n|---|---|---|\n");
        for (ws, dir) in recall {
            let count = std::fs::read_to_string(dir.join("index.jsonl"))
                .map(|s| s.lines().filter(|l| !l.trim().is_empty()).count())
                .unwrap_or(0);
            body.push_str(&format!(
                "| `{}` | `{}` | {count}件（全件未レビュー） |\n",
                ws.display(),
                dir.display()
            ));
        }
    }
    if let Some(combo) = combo {
        body.push_str(&format!(
            "\n## 欲張りセット（CoWとRecallが両方ある）\n\n\
             ワークスペース: `{}`\n\n\
             同じワークスペースに**未適用のCoW変更**と**未レビューのRecall記憶**が同時にある。\n\
             記憶はワークスペース単位（セッション単位ではない）なので、`combo-short`/`combo-long`の\n\
             どちらで起動しても未レビュー記憶は同じ5件が対象になる。\n\n\
             ```powershell\n\
             cd {}\n\
             harness.exe --staged --resume combo-short   # または combo-long\n\
             ```\n\n\
             - CoW側: `combo/SCENARIOS.md`（`/fsstage commit`でパネルが開く）\n\
             - Recall側: `{}`（checkpoint 8件のうち先頭3件がレビュー済み、残り5件が未レビュー。\n\
               `harness memory list`／TUIの`/memory`で見える）\n",
            combo.workspace.display(),
            combo.workspace.display(),
            combo.memory.display()
        ));
    }
    std::fs::write(out.join(MARKER), body).unwrap();
}
